# Generated by Django 5.2.9 on 2025-12-13 10:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработано')),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратные связи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название игры')),
                ('genre', models.CharField(choices=[('RPG', 'RPG'), ('Adventure', 'Adventure'), ('Puzzle', 'Puzzle'), ('Action', 'Action'), ('Strategy', 'Strategy'), ('Simulation', 'Simulation'), ('Sports', 'Sports'), ('Racing', 'Racing'), ('Horror', 'Horror'), ('FPS', 'First-Person Shooter'), ('MMO', 'Massively Multiplayer Online'), ('Indie', 'Indie'), ('Metroidvania', 'Metroidvania')], max_length=50, verbose_name='Жанр')),
                ('developer', models.CharField(max_length=200, verbose_name='Разработчик')),
                ('release_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1970), django.core.validators.MaxValueValidator(2030)], verbose_name='Год выпуска')),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
                ('platforms', models.CharField(choices=[('PC', 'PC'), ('PlayStation', 'PlayStation'), ('Xbox', 'Xbox'), ('Nintendo Switch', 'Nintendo Switch'), ('Mobile', 'Mobile'), ('Multiplatform', 'Multiplatform')], max_length=50, verbose_name='Платформы')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Рейтинг (0-10)')),
                ('description', models.TextField(verbose_name='Описание игры')),
                ('game_image', models.URLField(verbose_name='Обложка игры')),
                ('steam_url', models.URLField(verbose_name='Ссылка на Steam')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Тег')),
                ('slug', models.SlugField(unique=True, verbose_name='URL-имя')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название подборки')),
                ('description', models.TextField(verbose_name='Описание подборки')),
                ('is_public', models.BooleanField(default=True, verbose_name='Публичная подборка')),
                ('cover_image', models.URLField(blank=True, null=True, verbose_name='Обложка подборки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('likes_count', models.IntegerField(default=0, verbose_name='Количество лайков')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель подборки')),
            ],
            options={
                'verbose_name': 'Подборка',
                'verbose_name_plural': 'Подборки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GameCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок в подборке')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.collection', verbose_name='Подборка')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.game', verbose_name='Игра')),
            ],
            options={
                'verbose_name': 'Игра в подборке',
                'verbose_name_plural': 'Игры в подборках',
                'ordering': ['order'],
                'unique_together': {('collection', 'game')},
            },
        ),
        migrations.AddField(
            model_name='collection',
            name='games',
            field=models.ManyToManyField(related_name='collections', through='main.GameCollection', to='main.game'),
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameters', models.JSONField(default=dict, verbose_name='Параметры запроса')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата рекомендации')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.game', verbose_name='Рекомендованная игра')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Рекомендация',
                'verbose_name_plural': 'Рекомендации',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='game',
            name='tags',
            field=models.ManyToManyField(blank=True, to='main.tag', verbose_name='Теги для рекомендаций'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferences', models.JSONField(default=list, verbose_name='Предпочтения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('collections_count', models.IntegerField(default=0, verbose_name='Количество созданных подборок')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.game', verbose_name='Игра')),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранные игры',
                'ordering': ['-added_at'],
                'unique_together': {('user', 'game')},
            },
        ),
    ]
