# Generated by Django 5.2.9 on 2025-12-23 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='cover_image',
        ),
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.CharField(choices=[('RPG', 'RPG'), ('Adventure', 'Adventure'), ('Puzzle', 'Puzzle'), ('Action', 'Action'), ('Strategy', 'Strategy'), ('Simulation', 'Simulation'), ('Sports', 'Sports'), ('Racing', 'Racing'), ('Horror', 'Horror'), ('FPS', 'First-Person Shooter'), ('MMO', 'Massively Multiplayer Online'), ('Visual Novel', 'Visual Novel'), ('Metroidvania', 'Metroidvania'), ('Roguelike', 'Roguelike'), ('Tactical Shooter', 'Tactical Shooter'), ('Survival', 'Survival'), ('Shooter', 'Shooter'), ('Sandbox', 'Sandbox')], max_length=50, verbose_name='Жанр'),
        ),
        migrations.CreateModel(
            name='CollectionLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.collection', verbose_name='Подборка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лайк подборки',
                'verbose_name_plural': 'Лайки подборок',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'collection')},
            },
        ),
    ]
